site_name: PyAdd
plugins:
  - gen-files:
      scripts:
        - docs/generate_docs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths:
            '.'
  - section-index
nav:
  - Overview: index.md
  - Code Reference: ./